# Generated by Django 4.1.4 on 2022-12-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'medida', 'marca', 'precio')},
        ),
    ]
