# Generated by Django 4.1.4 on 2022-12-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenventa',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_c']},
        ),
    ]
